version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    restart: always

  tests:
    build: .
    container_name: fastapi_tests
    command: ["pytest", "-v"]
    volumes:
      - .:/usr/src/app
