version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development

  # Para testes (opcional)
  tests:
    build: .
    volumes:
      - .:/app
    command: python -m pytest -v
    depends_on:
      - fastapi-app    