name: CI WorkFlow
on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@main

    - name: linting
      uses: programmingwithalex/pylinter@main
      with:
        python-root: '.'
        flake8-flags: '--count --show-source --statistics'
        mypy-flags: '--ignore-missing-imports'
        fail-on-isort: false









# name: flake8 Lint

# on: [push, pull_request]

# jobs:
#   flake8-lint:
#     runs-on: ubuntu-latest
#     name: Lint
#     steps:
#       - name: Check out source repository
#         uses: actions/checkout@v3
#       - name: Set up Python environment
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.11"
#       - name: flake8 Lint
#         uses: py-actions/flake8@v2
