name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Instalar dependências
        run: pip install -r requirements.txt
      - name: Rodar testes
        run: pytest








# name: flake8 Lint

# on: [push, pull_request]

# jobs:
#   flake8-lint:
#     runs-on: ubuntu-latest
#     name: Lint
#     steps:
#       - name: Check out source repository
#         uses: actions/checkout@v3
#       - name: Set up Python environment
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.11"
#       - name: flake8 Lint
#         uses: py-actions/flake8@v2
